### ISSUE TITLE
Unable to detect Sonos One devices from local network.

### ISSUE THREAD

**Issue by danditomaso** [filahf/budgie-stream#15]
I wanted to mention I love this project and am really excited to start contributing to it. I've recently downloaded and installed Budgie on Windows 10 and after permitting it access through my local network, when you run the application and click "Select devices" button, the dialog pops up and it just keeps searching for device seemingly forever. I have a local network using a 192.168.1.x network without any other intermediate firewalls, on this local network I have two Sonos One devices. Is there any sort of troubleshooting I can do from the dev version in order to help expedite a fix for this?

**Comment by filahf** [comment]
Thank you for showing interest in the project, I really appreciate it!

Hmm yea that sounds odd, it's basically the same setup I'm running. If you run the dev environment the server should output logs regarding the device discovery (in your bash console, not the chrome dev one). The logs should help us narrow down the problem. Let me know how it goes

**Comment by danditomaso** [comment]
Yeah, here is the output from running the development server as you've listed the instructions in your readme and doing a yarn install. It looks like it's looking for a bindings file
``` App threw an error during load
[1] Error: Could not locate the bindings file. Tried:
[1]  → D:\code\budgie-stream\budgie-stream\node_modules\@suldashi\lame\build\bindings.node
[1]  → D:\code\budgie-stream\budgie-stream\node_modules\@suldashi\lame\build\Debug\bindings.node
[1]  → D:\code\budgie-stream\budgie-stream\node_modules\@suldashi\lame\build\Release\bindings.node
[1]  → D:\code\budgie-stream\budgie-stream\node_modules\@suldashi\lame\out\Debug\bindings.node
[1]  → D:\code\budgie-stream\budgie-stream\node_modules\@suldashi\lame\Debug\bindings.node
[1]  → D:\code\budgie-stream\budgie-stream\node_modules\@suldashi\lame\out\Release\bindings.node
[1]  → D:\code\budgie-stream\budgie-stream\node_modules\@suldashi\lame\Release\bindings.node
[1]  → D:\code\budgie-stream\budgie-stream\node_modules\@suldashi\lame\build\default\bindings.node
[1]  → D:\code\budgie-stream\budgie-stream\node_modules\@suldashi\lame\compiled\12.14.1\win32\x64\bindings.node
[1]  → D:\code\budgie-stream\budgie-stream\node_modules\@suldashi\lame\addon-build\release\install-root\bindings.node
[1]  → D:\code\budgie-stream\budgie-stream\node_modules\@suldashi\lame\addon-build\debug\install-root\bindings.node
[1]  → D:\code\budgie-stream\budgie-stream\node_modules\@suldashi\lame\addon-build\default\install-root\bindings.node
[1]  → D:\code\budgie-stream\budgie-stream\node_modules\@suldashi\lame\lib\binding\node-v80-win32-x64\bindings.node
[1]     at bindings (D:\code\budgie-stream\budgie-stream\node_modules\bindings\bindings.js:126:9)
[1]     at Object.<anonymous> (D:\code\budgie-stream\budgie-stream\node_modules\@suldashi\lame\lib\bindings.js:1:37)
[1]     at Module._compile (internal/modules/cjs/loader.js:967:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
[1]     at Module.load (internal/modules/cjs/loader.js:815:32)
[1]     at Module._load (internal/modules/cjs/loader.js:727:14)
[1]     at Function.Module._load (electron/js2c/asar.js:769:28)
[1]     at Module.require (internal/modules/cjs/loader.js:852:19)
[1]     at require (internal/modules/cjs/helpers.js:74:18)
[1]     at Object.<anonymous> (D:\code\budgie-stream\budgie-stream\node_modules\@suldashi\lame\lib\decoder.js:7:15)
[1] (node:7504) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by filahf** [comment]
I've had problems with that package as well. In my case a electron rebuild solved my problems.
Have a look at the steps presented here https://github.com/filahf/budgie-stream#common-errors , might solve your problems as well

**Comment by danditomaso** [comment]
Thanks for the instructions, I did the rebuild on that package and the dev environment started up. When I hit Select Devices I see the following in my bash console ```[1]
[1] [Function]
[1] (node:2380) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1] Https App started
[1]  Error in discovery {}
[1] undefined
```

**Comment by danditomaso** [comment]
Crises adverted, after a reboot the app appears to be working as expected! Thanks for taking time to work with me on this item.

**Comment by filahf** [comment]
Haha, what a relief! No worries. Thanks again for your interest in the project!
